// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

/// Reads ISO JSON (`all.json` from
/// https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json)
/// and writes `lib/screens/games/cards/nationality_iso_data.dart`.
///
/// Usage: `dart run tool/gen_nationality_iso.dart path/to/all.json`
void main(List<String> args) {
  if (args.isEmpty) {
    print('Usage: dart run tool/gen_nationality_iso.dart <all.json>');
    exit(1);
  }
  final list = jsonDecode(File(args.first).readAsStringSync()) as List<dynamic>;
  final alpha3To2 = <String, String>{};
  final nameTo2 = <String, String>{};
  for (final e in list) {
    final m = e as Map<String, dynamic>;
    final a2 = (m['alpha-2'] as String?)?.toUpperCase();
    final a3 = (m['alpha-3'] as String?)?.toUpperCase();
    final name = m['name'] as String?;
    if (a2 != null && a2.length == 2 && a3 != null && a3.length == 3) {
      alpha3To2[a3] = a2;
    }
    if (a2 != null && a2.length == 2 && name != null && name.isNotEmpty) {
      final key = _normNameKey(name);
      if (key.isNotEmpty) {
        nameTo2[key] = a2!;
      }
    }
  }
  // Common DB / UI aliases not matching official English names
  const extra = <String, String>{
    'UK': 'GB',
    'U K': 'GB',
    'GREAT BRITAIN': 'GB',
    'ENGLAND': 'GB',
    'SCOTLAND': 'GB',
    'WALES': 'GB',
    'N IRELAND': 'GB',
    'NORTHERN IRELAND': 'GB',
    'UNITED STATES': 'US',
    'AMERICA': 'US',
    'U S': 'US',
    'U S A': 'US',
    'USA': 'US',
    'LIBAN': 'LB',
    'LEB': 'LB',
    'LEBANESE': 'LB',
    'SYRIA': 'SY',
    'UAE': 'AE',
    'EMIRATES': 'AE',
    'KSA': 'SA',
    'SAUDI': 'SA',
    'IVORY COAST': 'CI',
    'DR CONGO': 'CD',
    'DRC': 'CD',
    'CONGO DR': 'CD',
    'SOUTH KOREA': 'KR',
    'NORTH KOREA': 'KP',
    'RUSSIA': 'RU',
    'CZECH REPUBLIC': 'CZ',
    'CZECHIA': 'CZ',
    'TURKEY': 'TR',
    'TURKIYE': 'TR',
    'HOLLAND': 'NL',
    'THE NETHERLANDS': 'NL',
    'BOSNIA': 'BA',
    'PALESTINE': 'PS',
    'TAIWAN': 'TW',
    'KOSOVO': 'XK',
    'MACAU': 'MO',
    'SWAZILAND': 'SZ',
    'CAPE VERDE': 'CV',
    'LAOS': 'LA',
    'VIETNAM': 'VN',
    'IRAN': 'IR',
    'MOLDOVA': 'MD',
    'BOLIVIA': 'BO',
    'VENEZUELA': 'VE',
    'TANZANIA': 'TZ',
    'BRITISH VIRGIN ISLANDS': 'VG',
    'US VIRGIN ISLANDS': 'VI',
    'STATE OF PALESTINE': 'PS',
    'COTE D IVOIRE': 'CI',
    'FYROM': 'MK',
    'MACEDONIA': 'MK',
    'NORTH MACEDONIA': 'MK',
  };
  for (final e in extra.entries) {
    nameTo2[_normNameKey(e.key)] = e.value;
  }

  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tool/gen_nationality_iso.dart — do not hand-edit.',
    )
    ..writeln(
      '// Source: ISO 3166 (lukes/ISO-3166-Countries-with-Regional-Codes all.json)',
    )
    ..writeln()
    ..writeln('const Map<String, String> kNationalityAlpha3ToAlpha2 = {');
  for (final e
      in alpha3To2.entries.toList()..sort((a, b) => a.key.compareTo(b.key))) {
    out.writeln("  '${e.key}': '${e.value}',");
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln('const Map<String, String> kNationalityNameKeyToAlpha2 = {');
  for (final e
      in nameTo2.entries.toList()..sort((a, b) => a.key.compareTo(b.key))) {
    out.writeln("  '${_escapeDartString(e.key)}': '${e.value}',");
  }
  out.writeln('};');

  final target = File('lib/screens/games/cards/nationality_iso_data.dart');
  target.writeAsStringSync(out.toString());
  print(
    'Wrote ${target.path} (${alpha3To2.length} alpha3, ${nameTo2.length} names)',
  );
}

String _normNameKey(String name) {
  final u = name.toUpperCase();
  final buf = StringBuffer();
  for (var i = 0; i < u.length; i++) {
    final c = u.codeUnitAt(i);
    final isAlnum = (c >= 0x30 && c <= 0x39) || (c >= 0x41 && c <= 0x5A);
    buf.writeCharCode(isAlnum ? c : 0x20);
  }
  return buf.toString().replaceAll(RegExp(r'\s+'), ' ').trim();
}

String _escapeDartString(String s) =>
    s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
