name: iOS-ipa-build

on:
  workflow_dispatch:

env:
  APP_VERSION: 1.0.0

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - name: Build iOS app
        run: >
          flutter build ios --release --no-codesign
          --build-name=$APP_VERSION
          --build-number=${{ github.run_number }}

      - name: Create Payload folder
        run: mkdir -p Payload
        working-directory: build/ios/iphoneos

      - name: Copy app bundle
        run: cp -R Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Package IPA
        run: >
          ditto -c -k --sequesterRsrc --keepParent
          Payload
          "${{ github.event.repository.name }}.ipa"
        working-directory: build/ios/iphoneos

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-ios-ipa-build-${{ github.run_number }}
          path: build/ios/iphoneos/${{ github.event.repository.name }}.ipa
